
glm:
  model: "bge_m3"
  base_url: "http://xxx:8000/v1"
  embedding_model: "bge_m3"

deepseek:

  # model: "Qwen3-14b"
  model: "qwen2.5"
  # model: "Qwen3-32b"

  api_key: "ollama"
  base_url: "http://localhost:8001/v1"

# Model Parameters
model_params:
  openai_embedding_dim: 1536
  glm_embedding_dim: 1024
  max_token_size: 8192

